# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoutesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='RoutesApp.Route'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='RoutesApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='routes',
            field=models.ManyToManyField(related_name='users', through='RoutesApp.Rating', to='RoutesApp.Route'),
        ),
    ]
