# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 19:23
from __future__ import unicode_literals

import Apps.BikeMe.bikemeutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeMe', '0003_auto_20170929_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.CharField(default=Apps.BikeMe.bikemeutils.BikeMeUtils.getCurrentDateString, max_length=100),
        ),
    ]
